config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get 'edit_basic_info'
      get "change_log"
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      patch "attendances/update_overwork_request"
      get "edit_orverwork_request"
    end
    resources :attendances, only: :update
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  # 「remember_token」という仮想の属性を作成します。
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :department, length: { in: 2..50 }, allow_blank: true
  validates :basic_time, presence: true
  validates :work_time, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返します。
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了します。
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def self.search(search)
    if search
      where(['name LIKE ?', "%#{search}%"])
    else
      all
    end
  end
end

app/controllers/users_controller.rb
require 'csv'
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info, :edit_orverwork_request]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy, :edit_basic_info, :update_basic_info]
  before_action :set_one_month, only: :show
  before_action :admin_or_correct_user, only: :show

  def index
    @users = User.all
    @users = User.paginate(page: params[:page])
    @users = @users.where('name LIKE ?', "%#{params[:search]}%") if params[:search].present?
  end
  

  def show
    respond_to do |format|
      format.html {
        @worked_sum = @attendances.where.not(started_at: nil).count
      }
      format.csv
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render :edit      
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end

  def edit_basic_info
    @user = User.find(params[:id])
  end

  def update_basic_info
    if @user.update_attributes(basic_info_params)
      flash[:success] = "#{@user.name}の基本情報を更新しました。"
    else
      flash[:danger] = "#{@user.name}の更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")
    end
    redirect_to users_url
  end
  
  def admin_or_correct_user
      @user = User.find(params[:user_id]) if @user.blank?
      unless current_user?(@user) || current_user.admin?
        flash[:danger] = "閲覧権限がありません。"
        redirect_to(root_url)
      end
  end
  
  def change_log
    @attendances = load_attendances
    if request.xhr?
      render '_change_logs', layout: false
    else
      render
    end
  end
  
  def edit_orverwork_request
    @day = Date.parse(params[:day])
    @attendance = @user.attendances.find_by(worked_on: @day)
    @attendances = []
  end
  
  def update_overwork_request
    @day = Date.parse(params[:day])
    @attendance = @user.attendances.find_by(worked_on: @day)
    params[:attendance][:next_day] == '1' ? Time.now.tomorrow : Time.now
    flash[:success] = "残業申請しました。"
    redirect_to @user
  end
  
  private
  
    def load_attendances
      @first_day = params[:y] && params[:m] ?
        Date.new(params[:y].to_i, params[:m].to_i, 1) : Date.current.beginning_of_month
      @last_day = @first_day.end_of_month
      current_user.attendances.where(worked_on: @first_day..@last_day).order(:worked_on)
    end
  
    def user_params
      params.require(:user).permit(:name, :email, :department, :password, :password_confirmation)
    end

    def basic_info_params
      params.require(:user).permit(:department, :basic_time, :work_time)
    end
    
end

app/helpers/users/searches_helper.rb
module Users::SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # 勤怠基本情報を指定のフォーマットで返します。  
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_change_logs.html.erb
<table class="table table-bordered table-condensed user-table">
  <tbody>
      <tr>
        <td>日付</td>
        <td colspan="2">変更前出社時間</td>
        <td colspan="2">変更前退社時間</td>
        <td colspan="2">変更後出社時間</td>
        <td colspan="2">変更後退社時間</td>
        <td>指示者</td>
        <td>承認日</td>
      </tr>
    <% @attendances.each do |attendance| %>
    <tr>
      <td><%= attendance.worked_on %></td>
      <td colspan="2"><%= attendance.id %></td>
      <td colspan="2"></td>
      <td colspan="2"></td>
      <td colspan="2"></td>
      <td></td>
      <td></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_edit_basic_info.html.erb
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <h1 class="modal-title">基本情報編集</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>

            <%= f.label :name, class: "label-#{yield(:class_text)}" %>
            <p><%= @user.name %></p>

            <%= f.label :department, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :department, class: "form-control" %>

            <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :basic_time, class: "form-control" %>

            <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :work_time, class: "form-control" %>

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_edit_orverwork_request.html.erb
<div class="modal fade" id="modal-target">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label>
          <span aria-hidden="true">&times;</span>
        </button>
        <h1 class="modal-title">【残業申請】</h1>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-10 col-md-offset-1">
            <%= form_with(model: @user, url: attendances_update_overwork_request_user_path(params:{ day: @attendance.worked_on }), local: true, method: :patch) do |f| %>
            <table class="table table-bordered table-condensed table-stiped user-table">
              <thead>
                <th>日付</th>
                <th>曜日</th>
                <th>終了予定時間</th>
                <th>翌日</th>
                <th>実務処理内容</th>
                <th>指示者確認㊞</th>
              </thead>
              
              <tbody>
                <% @attendances.each do |day| %>
                  <%= f.fields_for "attendances[]", day do |attendance| %>
                    <td><%= l(@day, format: :short) %></td>
                    <% if @day.wday == 6 %> <td class="sat"><%= $days_of_the_week[@day.wday] %></td>
                    <% elsif @day.wday == 0 %>
                      <td class="sun"><%= $days_of_the_week[@day.wday] %></td>
                    <% else %>
                      <td><%= $days_of_the_week[@day.wday] %></td>
                    <% end %>
                    <td><%= attendance.tiem_field :scheduled_end_timne, class: "form-control" %></td>
                    <td><%= attendance.check_box :next_day, id: "next_day" %></td>
                    <td><%= attendance.text_field :business_process, class: "form-control" %></td>
                    <td><%= attendance.select :cofirmation, [["なし", "なし"], ["申請中", "申請中"], ["承認", "承認"], ["否認", "否認"]], class: "form-controle" %></td>
                  <% end %>
                  <% end %>
              </tbody>
              
              <tfoot>
                <tr>
                  <td><%= Date.today.strftime('%m/%d') %></td>
                  <td><%= %w(日 月 火 水 木 金 土)[Date.today.wday] %></td>
                  <td><%= time_field :finished_at, class: "form-control" %></td>
                  <td><%= check_box :next_day, id: "next_day" %></td>
                  <td><%= text_field :business_process, class: "form-control" %></td>
                  <td><%= select_tag :superior, options_for_select(["上長A", "上長B"]), include_blank: "なし", class: "form_control" %></td>
                  </td>
                </tr>
              </tfoot>
              
            </table>
            
            <div class="center">
              <%= f.submit "変更を送信する", class: "btn btn-default btn-block btn-user" %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :department, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :department, class: "form-control" %>
  
  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/change_log.html.erb
<%
  select_begin_year = 2012
  select_end_year = Date.current.year
%>
<% provide(:title, "勤怠ログ") %>
<h1>勤怠ログ</h1>
<div class="pull-left">
  <%= form_tag(change_log_user_path(current_user), method: "get", remote: true, id: 'search_change_log_form') do %>
    <%= select_tag('y', options_for_select((select_begin_year..select_end_year).map{|i| ["#{i}年", i] }, @first_day.year)) %>
    <%= select_tag('m', options_for_select((1..12).map{|i| ["#{i}月", i] }, @first_day.month)) %>
    <%= submit_tag "検索", name:nil, class: "btn btn-default" %>
  <% end %>
</div>

<div id ='change_logs'>
  <%= render 'change_logs' %>
</div>

<script>
  $('#search_change_log_form').on('ajax:success', function(date) {
    var body = date.detail[2].response
    $('#change_logs').html(body)
  })
</script>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '編集') %>
<h1>ユーザー情報編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>

<div>
  <div>
    <div>
      <h1>基本情報編集</h1>
    </div>
    <div>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>
            
            <%= f.label :id, class: "label-#{yield(:class_text)}" %>
            <p><%= format("%04<number>d", number: @user.id) %></p>

            <%= f.label :name, class: "label-#{yield(:class_text)}" %>
            <p><%= @user.name %></p>

            <%= f.label :department, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :department, class: "form-control" %>

            <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :basic_time, class: "form-control" %>

            <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :work_time, class: "form-control" %>

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" >
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit_orverwork_request.js.erb
$("#edit_orverwork_request").html("<%= escape_javascript(render 'edit_orverwork_request') %>");
$("#modal-target").modal("show");

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<h1>全てのユーザー</h1>
  
<div class="col-md-10 col-md-offset-1">
  <%= will_paginate %>
  
  <div class="pull-right">
      ユーザー名検索
      <%= form_tag(users_path, method: "get") do %>
        <%= text_field_tag :search %>
        <%= submit_tag "検索", name:nil, class: "btn btn-primary" %>
      <% end %>
    </div>
  

<div class="col-md-10 col-md-offset-1">
  <table class="table table-condensed table-hover" id="table-users">
    <thead>
      <tr>
        <th><%= User.human_attribute_name :name %></th>
        <th></th>
        <th class="center"><%= User.human_attribute_name :department %></th>
        <% if current_user.admin? %>
          <th class="center"><%= User.human_attribute_name :basic_time %></th>
          <th class="center"><%= User.human_attribute_name :work_time %></th>
        <% end %>
        <th></th>
      </tr>
    </thead>

    <% @users.each do |user| %>
      <tr>
        <td>
          <% if current_user.admin? %>
            <%= link_to user.name, user %>
          <% else %>
            <%= user.name %>
          <% end %>
        </td>
        <td class="center">
          <% if current_user.admin? && !current_user?(user) %>
            <%= link_to "基本情報編集", edit_basic_info_user_path(user), remote: true, class: "btn btn-default" %>
            <%= link_to "削除", user, method: :delete,
                data: { confirm: "削除してよろしいですか？" }, class: "btn btn-default" %>
          <% end %>
        </td>
        <td class="center"><%= user.department.present? ? user.department : "未所属" %></td>
        <% if current_user.admin? %>
          <td class="center"><%= format_basic_info(user.basic_time) %></td>
          <td class="center"><%= format_basic_info(user.work_time) %></td>
        <% end %>
        
      </tr>
    <% end %>
  </table>
  <%= will_paginate %>
</div>
</div>

<!--モーダルウインドウ表示-->
<div id="edit-basic-info" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規登録') %>
<h1>ユーザー登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.csv.erb
<%== CSV.generate do |csv|
    # NOTE: 列が追加された場合はココに追加
    csv << %w(日付 出社 退社 備考)
    @attendances.each do |attendance|
      # NOTE: 列が追加された場合はココにも追加
      csv << [
        attendance.worked_on,
        attendance.started_at_rounded,
        attendance.finished_at_rounded,
        attendance.note,
      ]
    end
  end
%>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div>
  <div id="edit_orverwork_request" >
  </div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <td>
        <%= link_to "←", user_path(date: @first_day.prev_month), class: "btn btn-default" %>
        <%= l(@first_day, format: :middle) %>時間管理表
        <%= link_to "→", user_path(date: @first_day.next_month), class: "btn btn-default" %>
      </td>
      <td colspan="3">
        指定勤務開始時間：<%= format_basic_info(@user.work_time) %>
        
      </td>
      <td>基本時間：<%= format_basic_info(@user.basic_time) %></td>
      <td>初日 <%= l(@first_day, format: :short) %></td>
    </tr>

    <tr>
      <td>所属<%= @user.department.present? ? @user.department : "未所属" %></td>
      <td>氏名：<%= @user.name %></td>
      <td>コード</td>
      <td></td>
      <td>出勤日数 <%= @worked_sum %>日</td>
      <td>締め <%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>
 
<div class="btn-users-show">
  <% if %>
    <br><%= link_to "【所属長申請のお知らせ】", "#" %>
    <br><%= link_to "【勤務変更のお知らせ】", "#" %>
    <br><%= link_to "【残業申請のお知らせ】", "#" %>
  <% end %>
  <br><%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-default" %>
  <%= link_to "CSV出力", user_path(format: :csv, date: @first_day), class: "btn btn-default" %>
</div>
<div class="btn-users-show">
  <%= link_to "勤怠修正ログ(承認済み)", change_log_user_path, class: "btn btn-default" %>
</div>
<div>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th rowspan="3">残業申請</th>
        <th rowspan="3">日付</th>
        <th rowspan="3">曜日</th>
        <th rowspan="3">出勤・退勤ボタン</th>
        <th colspan="6">【実績】</th>
        <th colspan="6">所定外勤務</th>
      </tr>
      <tr>
        <th colspan="2">勤怠</th>
        <th colspan="2">退勤</th>
        <th rowspan="2">在社時間</th>
        <th rowspan="2">備考</th>
        <th colspan="2">終了予定時間</th>
        <th rowspan="2">時間外時間</th>
        <th rowspan="2">業務処理内容</th>
        <th rowspan="2">指示確認㊞</th>
      </tr>
      <tr>
        <th>時</th>
        <th>分</th>
        <th>時</th>
        <th>分</th>
        <th>時</th>
        <th>分</th>
      </tr>
    </thead>

    <tbody>
      <% @attendances.each do |day| %>
        <% css_class =
          case $days_of_the_week[day.worked_on.wday]
          when '土'
            'text-primary'
          when '日'
            'text-danger'
          end
        %>
        
        <tr>
          <td><%= link_to "残業申請", edit_orverwork_request_user_path(@user, params:{ day: day.worked_on }), remote: true, class: "btn btn-default" %></td>
          <td><%= l(day.worked_on, format: :short) %></td>
          <td class="<%= css_class %>"><%= $days_of_the_week[day.worked_on.wday] %></td>
          <td>
            <% if btn_text = attendance_state(day) %>
              <%= link_to "#{btn_text}", user_attendance_path(@user, day), method: :patch, class: "btn btn-default btn-attendance" %>
            <% end %>
          </td>
          <td>
            <%= l(day.started_at_rounded, format: :hour) if day.started_at_rounded.present? %>
          </td>
          
          <td>
            <%= l(day.started_at_rounded, format: :minute) if day.started_at_rounded.present? %>
          </td>
          <td>
            <%= l(day.finished_at_rounded, format: :hour) if day.finished_at_rounded.present? %>
          </td>
          <td>
            <%= l(day.finished_at_rounded, format: :minute) if day.finished_at_rounded.present? %>
          </td>
          <td>
            <% if day.started_at_rounded.present? && day.finished_at_rounded.present? %>
              <%= str_times = working_times(day.started_at_rounded, day.finished_at_rounded) %>
              <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% end %>
          </td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td><%= day.note %></td>
          <td><%= day.superior %></td>
          
        </tr>
      <% end %>
    </tbody>

    <tfoot>
      <tr>
        <td colspan="2">累計日数</td>
        <td colspan="6">総合勤務時間</td>
        <td>累計</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td colspan="1">上長承認</td>
      </tr>
      <!--rowspan:縦結合、colspan：横結合-->
      <tr>
        <td colspan="2"><%= @attendances.count %></td>
        <td colspan="6"><%= format_basic_info(@user.work_time).to_f * @worked_sum %></td>
        <td><%= format("%.2f", @total_working_times.to_f) %></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td colsapan="1"></td>
      </tr>
    </tfoot>    
  </table>
</div>